### ISSUE TITLE
OParl OpenData für Ihr Rat- oder Kreishaus

### ISSUE THREAD

**Issue by ManAnRuck** [justcomplaining/DigitaleDemokratie#1]
danke für deine guten Kommentare bei https://github.com/demokratie-live/ :)

beschäftige mich gerade damit, nicht nur den Bundestag abzubilden, sondern auch lokalere ebenen.
Da ist OParl recht interessant und passt ggf. auch mit auf die liste hier, welche ich übrigens super und sehr hilfreich finde :)
https://oparl.org

**Comment by justcomplaining** [comment]
Sehr cool, danke!

Ich habe den Tip direkt eingefügt 👍
